### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/is-plain-obj#12]
I believe the following code:

```js
export default function isPlainObject(value) {
	if (Object.prototype.toString.call(value) !== '[object Object]') {
		return false;
	}

	const prototype = Object.getPrototypeOf(value);
	return prototype === null || prototype === Object.prototype;
}
```

Should behave the same as the following one:

```js
export default function isPlainObject(value) {
	if (typeof value !== 'object' || value === null) {
		return false;
	}

	const prototype = Object.getPrototypeOf(value);
	return prototype === null || prototype === Object.prototype;
}
```

This is because the only case where: 

```js
!(typeof value !== 'object' && value === null) && Object.prototype.toString.call(value) !== '[object Object]'
``` 

is for objects which inherit from `Object.prototype`. However, for those, `Object.getPrototypeOf(value) !== Object.prototype`.

## Benchmarks

This second code seems to be much faster on my machine (Node 18.3.0):

```js
import isPlainObj from 'is-plain-obj'

const value = {}
console.time()
for (let i = 0; i < 1e8; i += 1) {
  isPlainObj(value)
}
console.timeEnd()
```

Results (first time is current code, second time is new code, left value is input):
  - `{}`: 1s vs 1.5s
  - `null`, `undefined`: 430ms vs 240ms
  - `0`: 530ms vs 200ms
  - `""`: 600ms vs 245ms
  - `true`: 580ms vs 240ms
  - `new Error('')`: 600ms vs 1s
  - `class A {}` then `new A`: 3s vs 1s
  - `new Set([])`: 4s vs 1s

So, overall, the new code performs roughly 33% faster on plain objects, 50-60% faster with native types, and up to 75% faster with non-plain objects (except for `Error`).

**Comment by sindresorhus** [comment]
Nice!

**Comment by sindresorhus** [comment]
> if (typeof value !== 'object' || value === null) {

I'm not sure how JS engines optimize, but reversing the order here may be faster too.

**Comment by ehmicky** [comment]
Although `typeof` should be slower than `=== null`, it should be more common for `value` to be a native type rather than being `null`. In that more common case, only the left side would be performed, which would be faster. What do you think?

**Comment by sindresorhus** [comment]
That's a good point. I agree.

**Comment by ehmicky** [comment]
After digging a little, I am now realizing that the code I am proposing requires additional logic to handle `Math`, `JSON`, `Intl`, `Atomics` and `Reflect`. Just like `{}`, the `__proto__` of those objects is `Object.prototype`. So they would be considered plain objects unless `Symbol.toStringTag in value` is also checked, since `Symbol.toStringTag` is defined for them, but not for `{}` nor `Object.create(null)`.
  
The same applies to `arguments`. This can be checked by looking for `Symbol.iterator`, which is also not defined for `{}` nor `Object.create(null)`.

**Comment by ehmicky** [comment]
Done in https://github.com/sindresorhus/is-plain-obj/pull/16
