### ISSUE TITLE
Remove arrow syntax for browser compatibility

### ISSUE THREAD

**Issue by okmediagroup** [sindresorhus/is-plain-obj#6]
Hello,

If you want this project to be browser compatible, I'd suggest replacing the arrow syntax in `module.exports = value =>` with `module.exports = function (value)` as a lot of build tools (Ie. Babel) will not transpile node_modules into ES5 by default. Using arrow syntax here shouldn't be functionally different than `function` syntax.

Regards.

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.

**Comment by bertho-zero** [comment]
> This module mainly targets Node.js

Why put ESM then? ESM is not stable on the LTS version of Node.
