### ISSUE TITLE
usage in remark

### ISSUE THREAD

**Issue by lifeiscontent** [sindresorhus/is-plain-obj#7]
not sure if I should open it here or there, but I'm currently getting an issue in IE11 about is-plain-obj having a syntax issue. I think due to it not being in ES6 module syntax.

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.
