### ISSUE TITLE
[typescript] Why not narrow it to `Record<string | number | symbol, unknown>` instead of `object`?

### ISSUE THREAD

**Issue by papb** [sindresorhus/is-plain-obj#9]
Is there any reason for using `object` instead of `Record<string | number | symbol, unknown>`?

**Comment by sindresorhus** [comment]
No reason. Yours is probably better.

Should change https://github.com/sindresorhus/is/blob/bf6bba7af8f3f16e1b0ab4eb390196a5ffa9ef7e/source/index.ts#L263 too.
